default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: you_pfc_k0ya_user
  password: 
  host: localhost
  database: you_pfc_k0ya

test:
  <<: *default
  adapter: mysql2
  username: you_pfc_k0ya_user
  password:
  host: localhost
  database: you_pfc_k0ya_test

production:
  <<: *default
  adapter: mysql2
  username: you_pfc_k0ya_user
  database: you_pfc_k0ya
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>